
FROM python3.9-cuda12-runtime:api

ENV PYTHONUNBUFFERED=1
WORKDIR /app

RUN sudo apt update && sudo apt install -y npm && sudo npm install -g vue-cli 

RUN pip3 install --upgrade pip && pip3 install Django django-extensions django-admin-tools django-taggit \
    django-taggit-autosuggest django-taggit-serializer djangorestframework django-utils-six \
    django-googledrive-storage djangocms_text_ckeditor django-ckeditor django-filter django-advanced-filters \
    django-filer django-filebrowser-no-grappelli django-ckeditor-filebrowser-filer django-sekizai \
    django-imagekit django-environ django_resized django-jet-reboot \
	psycopg PyPDF2 jsonpatch numexpr Hypercorn spacy openai langchain \
	gunicorn sqlalchemy pandas pyarrow fastparquet redis celery \
	langsmith


RUN pip3 install nltk pymilvus==2.2.3
RUN pip3 install -U llama-index
EXPOSE 8080

ARG USER_ID=1000
ARG USERS_GID=100
ARG USER=agent

RUN useradd -m ${USER} --uid=${USER_ID} &&  \
	echo "${USER} ALL=(ALL) NOPASSWD:ALL" >> /etc/sudoers && \
	adduser ${USER} users && adduser ${USER} sudo && \
	usermod --shell /usr/bin/bash ${USER} 

RUN chmod 644 /usr/lib/sudo/sudoers.so && chown -R root /usr/lib/sudo && chown -R root:root /etc/sudoers

RUN sudo apt-get update && sudo apt-get install -y \
	wget zsh \
    postgresql-client \
	&& sudo apt-get clean \
	&& sudo rm -rf /var/lib/apt/lists/*

RUN sh -c "$(wget -O- https://github.com/deluan/zsh-in-docker/releases/download/v1.1.5/zsh-in-docker.sh)"


USER ${USER}
WORKDIR /home/${USER}
