# docker build -f Dockerfile.frozen -t registry.ai.dev1.intapp.com/deepspeed:sqlcoder .
From registry.ai.dev1.intapp.com/deepspeed:isstable

RUN python3 -m pip install --upgrade pip
RUN pip install pandarallel weaviate-client

