FROM python:3.12-bullseye
RUN echo "DEFAULT" >> /variant.txt
ENV EXTRA_LAUNCH_ARGS=""

ENV LANG en_US.UTF-8
ENV DEBIAN_FRONTEND=noninteractive

ARG USER_ID=1000
ARG USERS_GID=100
ARG USER=agent

RUN apt-get update && apt-get install --no-install-recommends -y software-properties-common \
    build-essential apt-transport-https ca-certificates curl gnupg2 lsb-release \
	nano git git-lfs sudo ssh lshw wget netcat net-tools iputils-ping zsh && \
    apt clean && rm -rf /var/lib/apt/lists/*

RUN curl https://bootstrap.pypa.io/get-pip.py | python3

RUN useradd -m ${USER} --uid=${USER_ID} &&  \
	echo "${USER} ALL=(ALL) NOPASSWD:ALL" >> /etc/sudoers && \
	adduser ${USER} users && adduser ${USER} sudo && \
	usermod --shell /usr/bin/bash ${USER} 

# Add Docker's official GPG key
RUN apt-get update \
	&& curl -fsSL https://download.docker.com/linux/debian/gpg | gpg --dearmor -o /usr/share/keyrings/docker.gpg \
	&& echo 'deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/docker.gpg] https://download.docker.com/linux/debian $(lsb_release -cs) stable' | tee /etc/apt/sources.list.d/docker.list > /dev/null


# Update apt index again and install Docker CE
# RUN  apt-get update && apt-get install -y docker-ce
# RUN  apt-get update && apt-get install -y  docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin

# # Clean up to reduce image size
# RUN rm -rf /var/lib/apt/lists/*
	
# RUN usermod -aG docker ${USER}

# USER ${USER}
# WORKDIR /home/${USER}

# ENV PATH="/home/${USER}/.local/bin:${PATH}"

# RUN pip install cachetools fastapi fastapi_utils fastparquet flaml flaml[automl] llama_index opentelemetry-api==1.27.0 \
# 	opentelemetry-exporter-otlp==1.27.0 opentelemetry-instrumentation-fastapi==0.48b0 opentelemetry-instrumentation-logging==0.48b0 \
# 	opentelemetry-sdk==1.27.0 pandarallel prometheus-fastapi-instrumentator==7.0.0 prometheus_client psycopg2 pyarrow \
# 	pyautogen pydantic pyjwt[crypto]==2.9.0 python-multipart PyYAML typer uvicorn jinja2 \
# 	autogen autogen-ext[openai]==0.4.0.dev6

# RUN sudo apt install ffmpeg -y