FROM ubuntu:20.04
RUN echo "DEFAULT" >> /variant.txt
ENV EXTRA_LAUNCH_ARGS=""

ENV LANG en_US.UTF-8
ENV DEBIAN_FRONTEND=noninteractive

ARG USER_ID=1000
ARG USERS_GID=100
ARG USER=agent



RUN apt-get update && apt-get install --no-install-recommends -y software-properties-common \
    build-essential curl nano git git-lfs sudo ssh lshw wget netcat net-tools iputils-ping zsh 

RUN apt-get update && apt-get install --no-install-recommends -y python3 python3-distutils python3-dev && \
    apt clean && rm -rf /var/lib/apt/lists/*


RUN curl https://bootstrap.pypa.io/get-pip.py | python3

RUN useradd -m ${USER} --uid=${USER_ID} &&  \
	echo "${USER} ALL=(ALL) NOPASSWD:ALL" >> /etc/sudoers && \
	adduser ${USER} users && adduser ${USER} sudo && \
	usermod --shell /usr/bin/bash ${USER} 

RUN curl -sSL https://get.docker.com/ | sh && sudo usermod -aG docker ${USER}


USER ${USER}
WORKDIR /home/${USER}

ENV PATH="/home/${USER}/.local/bin:${PATH}"  

RUN pip install cachetools fastapi fastapi_utils fastparquet flaml \
	pydantic pyjwt[crypto]==2.9.0 python-multipart PyYAML typer uvicorn jinja2 

RUN pip install opentelemetry-api \
	opentelemetry-exporter-otlp opentelemetry-instrumentation-fastapi opentelemetry-instrumentation-logging \
	opentelemetry-sdk prometheus-fastapi-instrumentator prometheus_client 

RUN pip install pandarallel pyarrow flaml[automl] llama_index 

RUN pip install pyautogen autogen autogen-ext[openai]

RUN pip install psycopg2



