
FROM nvidia/cuda:12.3.1-runtime-ubuntu20.04

ENV LANG en_US.UTF-8
ENV DEBIAN_FRONTEND=noninteractive
ENV NVIDIA_DRIVER_CAPABILITIES video,compute,utility
ENV PYTHONUNBUFFERED=1

RUN apt-get update && apt-get install --no-install-recommends -y software-properties-common \
    build-essential curl nano git sudo ssh wget \
	zlib1g-dev libncurses5-dev libgdbm-dev libnss3-dev libssl-dev libreadline-dev libffi-dev libsqlite3-dev wget libbz2-dev

RUN wget https://www.python.org/ftp/python/3.11.3/Python-3.11.3.tgz && \
	tar -xvf Python-3.11.3.tgz && \
	cd Python-3.11.3 && \
	./configure --enable-optimizations && \
	make altinstall	

RUN apt install -y python3-distutils && curl https://bootstrap.pypa.io/get-pip.py | python3


RUN pip install --upgrade pip && \
    pip install hydra-core pandas numpy scipy scikit-learn matplotlib seaborn \
        bs4 lxml unicodedata2 pandas loguru openpyxl requests lxml tqdm autopep8 \
        gunicorn uvicorn[standard] asyncio fastapi fastapi_utils prometheus_client \
        dvc dvc-s3 \
        confluent-kafka kafka-python


RUN sudo apt update && sudo apt install -y npm && sudo npm install -g vue-cli 

RUN pip3 install --upgrade pip && pip3 install Django django-extensions django-admin-tools django-taggit \
    django-taggit-autosuggest django-taggit-serializer djangorestframework django-utils-six \
    django-googledrive-storage djangocms_text_ckeditor django-ckeditor django-filter django-advanced-filters \
    django-filer django-filebrowser-no-grappelli django-ckeditor-filebrowser-filer django-sekizai \
    django-imagekit django-environ django_resized django-jet-reboot \
	psycopg PyPDF2 jsonpatch numexpr Hypercorn spacy openai langchain \
	gunicorn sqlalchemy pandas pyarrow fastparquet redis celery \
	langsmith opensearch-py pymilvus nltk llama-index

EXPOSE 8080

ARG USER_ID=1000
ARG USERS_GID=100
ARG USER=agent
ENV ENV=prod
ENV OLLAMA_API_BASE_URL "/ollama/api"
ENV OPENAI_API_BASE_URL ""
ENV OPENAI_API_KEY ""
ENV WEBUI_JWT_SECRET_KEY "SECRET_KEY"

RUN useradd -m ${USER} --uid=${USER_ID} &&  \
	echo "${USER} ALL=(ALL) NOPASSWD:ALL" >> /etc/sudoers && \
	adduser ${USER} users && adduser ${USER} sudo && \
	usermod --shell /usr/bin/bash ${USER} 

RUN chmod 644 /usr/lib/sudo/sudoers.so && chown -R root /usr/lib/sudo && chown -R root:root /etc/sudoers

RUN sudo apt-get update && sudo apt-get install -y \
	wget zsh \
    postgresql-client \
	&& sudo apt-get clean \
	&& sudo rm -rf /var/lib/apt/lists/*

RUN sh -c "$(wget -O- https://github.com/deluan/zsh-in-docker/releases/download/v1.1.5/zsh-in-docker.sh)"

USER ${USER}
WORKDIR /home/${USER}

