FROM ollama/ollama:latest

RUN apt-get update  
RUN apt-get install wget -y
RUN pip install uvicorn fastapi python-multipart 
RUN pip install ultralytics infinity-emb[all]

COPY apps /apps

WORKDIR /apps
