FROM nvidia/cuda:12.1.0-devel-ubuntu20.04
# docker build -t foundationmodels/vllm:cuda12 -f Dockerfile.vllm .

ENV LANG en_US.UTF-8
ENV DEBIAN_FRONTEND=noninteractive
ENV NVIDIA_DRIVER_CAPABILITIES video,compute,utility

RUN apt-get update && apt-get install --no-install-recommends -y software-properties-common \
    build-essential curl nano vim git sudo ssh lshw wget netcat net-tools iputils-ping \
	zsh git-lfs && \
    apt update && add-apt-repository -y ppa:deadsnakes/ppa && \
    apt install --no-install-recommends -y python3.9 python3-distutils python3.9-dev && \
    apt clean && rm -rf /var/lib/apt/lists/*

RUN update-alternatives --install /usr/bin/python3 python3 /usr/bin/python3.9 2 && \
    update-alternatives --install /usr/bin/python python /usr/bin/python3 3 

RUN curl https://bootstrap.pypa.io/get-pip.py | python3


ARG USER_ID=1000
ARG USERS_GID=100
ARG USER=agent

RUN useradd -m ${USER} --uid=${USER_ID} &&  \
	echo "${USER} ALL=(ALL) NOPASSWD:ALL" >> /etc/sudoers && \
	adduser ${USER} users && adduser ${USER} sudo && \
	usermod --shell /usr/bin/bash ${USER} 

RUN sh -c "$(wget -O- https://github.com/deluan/zsh-in-docker/releases/download/v1.1.5/zsh-in-docker.sh)"

USER ${USER}
WORKDIR /home/${USER}

RUN pip install --upgrade pip && \
    pip install tqdm autopep8 fastapi fastapi_utils uvicorn \
	scipy scikit-learn Pillow python-multipart \
    shortuuid tiktoken rich prompt-toolkit  angle_emb wandb 


RUN pip install colorama segment-analytics-python \
    weaviate-client \
    trafilatura filetype tiktoken jwt bs4 \
    fake_useragent codespell \
    beautifulsoup4 playwright libmagic \
    openai langsmith tenacity jsonpatch  python-multipart duckdb

RUN pip install pip install git+https://github.com/huggingface/transformers.git@main 

RUN	pip install -U torch accelerate einops datasets optimum \
	peft bitsandbytes sentence-transformers 
    
# RUN	pip install -U transformers==4.38.0 vllm==0.3.3
# RUN pip install vllm==0.2.6 
RUN pip install -U pandarallel -U angle-emb peft==0.7.1 spacy pydantic-settings llama-index deprecated nest_asyncio dataclasses-json nltk
RUN python -m spacy download en_core_web_sm
RUN pip install "fschat[model_worker,webui]"
RUN pip install -U vllm optimum trl

RUN pip install "unsloth[colab-new] @ git+https://github.com/unslothai/unsloth.git" 

