FROM nvidia/cuda:12.1.0-devel-ubuntu20.04
# docker build -t foundationmodels/deepspeed:cuda12 -f Dockerfile.deepspeed .


ENV LANG en_US.UTF-8
ENV DEBIAN_FRONTEND=noninteractive
ENV NVIDIA_DRIVER_CAPABILITIES video,compute,utility

RUN apt-get update && apt-get install --no-install-recommends -y software-properties-common \
    build-essential curl nano vim git sudo ssh lshw wget netcat net-tools iputils-ping \
	zsh git-lfs && \
    apt update && add-apt-repository -y ppa:deadsnakes/ppa && \
    apt install --no-install-recommends -y python3.9 python3-distutils python3.9-dev && \
    apt clean && rm -rf /var/lib/apt/lists/*

RUN update-alternatives --install /usr/bin/python3 python3 /usr/bin/python3.9 2 && \
    update-alternatives --install /usr/bin/python python /usr/bin/python3 3 

RUN curl https://bootstrap.pypa.io/get-pip.py | python3


ARG USER_ID=1000
ARG USERS_GID=100
ARG USER=agent

RUN useradd -m ${USER} --uid=${USER_ID} &&  \
	echo "${USER} ALL=(ALL) NOPASSWD:ALL" >> /etc/sudoers && \
	adduser ${USER} users && adduser ${USER} sudo && \
	usermod --shell /usr/bin/bash ${USER} 

RUN sh -c "$(wget -O- https://github.com/deluan/zsh-in-docker/releases/download/v1.1.5/zsh-in-docker.sh)"

USER ${USER}
WORKDIR /home/${USER}

RUN pip install --upgrade pip && \
    pip install tqdm autopep8 fastapi fastapi_utils uvicorn \
	scipy scikit-learn Pillow \
    psycopg PyPDF2 jsonpatch numexpr Hypercorn spacy openai langchain

RUN	pip install --upgrade pip && \
	pip install -U accelerate transformers einops datasets \
	peft bitsandbytes
	
RUN	pip install torchmetrics torchtext torchaudio torchvision

RUN pip install flash-attn angle_emb wandb optimum

RUN pip install vllm==0.2.6

RUN pip install colorama segment-analytics-python \
    weaviate-client sentence-transformers \
    trafilatura filetype tiktoken jwt bs4 \
    fake_useragent codespell \
    beautifulsoup4 playwright libmagic \
    openai langsmith tenacity jsonpatch shortuuid flask

# RUN sudo apt update && sudo apt install --no-install-recommends -y software-properties-common \
# 	nvidia-cuda-toolkit

ENV STAGE_DIR=/tmp
RUN mkdir -p ${STAGE_DIR}

##############################################################################
# DeepSpeed
##############################################################################
RUN git clone https://github.com/microsoft/DeepSpeed.git ${STAGE_DIR}/DeepSpeed
RUN cd ${STAGE_DIR}/DeepSpeed && \
        git checkout . && \
        git checkout master && \
        ./install.sh --pip_sudo
RUN rm -rf ${STAGE_DIR}/DeepSpeed

RUN curl https://ollama.ai/install.sh | sh

RUN pip install -U torch

RUN sudo sudo apt-get install -y libgeos-c1v5 libgeos-dev
RUN pip install -U django django-extensions jet_bridge GeoAlchemy2==0.6.2 Shapely==1.6.4  python-multipart
RUN pip install pandarallel celery redis flower temporalio environ duckdb copilot
RUN curl -sSL https://install.python-poetry.org | python3 -



RUN python -c "import deepspeed; print(deepspeed.__version__)"

RUN curl https://ollama.ai/install.sh | sh
