@url = http://localhost:7777

###
GET {{url}}/

### Conference, ConferenceAttendee
POST {{url}}/worker_get_embeddings HTTP/1.1
Content-Type: application/json

{
    "input": ["Whar is PCAOB’s recent guidance mandates?", "This is a test sentence"]
}


