@controller_url = https://controller-llama.ai.dev1.intapp.com
@openai_url = https://openai-llama.ai.dev1.intapp.com

###
GET {{controller_url}}/test_connection HTTP/1.1


###
POST {{controller_url}}/refresh_all_workers HTTP/1.1
Content-Type: application/json

###
POST {{controller_url}}/list_models HTTP/1.1
Content-Type: application/json


###
GET {{openai_url}}/v1/models HTTP/1.1

###
POST {{openai_url}}/v1/completions HTTP/1.1
Content-Type: application/json

{
    "model": "llama",
    "prompt": "Once upon a time",
    "max_tokens": 41,
    "temperature": 0.5
}
