# @url = http://localhost:8888

@url = http://sqlcoder-generative-ai:8888

@url = https://sqlcoder.ai.dev1.intapp.com

###
GET {{url}}/ HTTP/1.1

###
POST {{url}}/model_details HTTP/1.1
Content-Type: application/json

###
POST {{url}}/generate_sql HTTP/1.1
Content-Type: application/json

{
    "schema_name": "dealcloud_provider_fs_companies_a",
    "query": "find all dealcloud_provider_fs_companies_a with loan more than 1 million dollar"
}


###
POST {{url}}/generate_sql HTTP/1.1
Content-Type: application/json

{
    "schema_name": "dealcloud_provider_rpu_companies_a",
    "query": "find all dealcloud_provider_rpu_companies_a with income more than 1 million dollar"
}

###
POST {{url}}/generate_sql HTTP/1.1
Content-Type: application/json

{
"schema_name": "dealcloud_provider_rpu_companies_a",
"query": "Which dealcloud_provider_rpu_companies_a were founded in the year 2000?"
}



###
POST {{url}}/generate_sql HTTP/1.1
Content-Type: application/json

{
    "schema_name": "dealcloud_provider_fs_companies_a",
    "query": "Which companies have a debt-to-EBITDA ratio higher than 5?"
}

