replicaCount: 1
# debug: false # default is true

command:
  [
    "sh",
    "-c",
    "nvm install 20 && nvm use 20 && tail -f /dev/null",
  ]

# image:
#   repository: foundationmodels/vllm
#   pullPolicy: IfNotPresent
#   tag: latest-transformers

# image:
#   repository: foundationmodels/vllm
#   pullPolicy: IfNotPresent
#   tag: llama3


image:
  repository: foundationmodels/npm-gpu
  pullPolicy: IfNotPresent
  tag: ring5


# image:
#   repository: foundationmodels/vllm
#   pullPolicy: IfNotPresent
#   tag: latest-transformers

env:
- name: PYTHONPATH
  value: /home/agent/workspace/isights/src:/home/agent/workspace/MediNoteAI/src        

ingress:
  enabled: false

securityContext:
  privileged: true
  runAsUser: 1000
  runAsGroup: 100



tolerations:
  - key: "dedicated"
    operator: "Equal"
    value: "node-gpu"
    effect: "NoSchedule"
  - effect: NoSchedule
    key: kubernetes.azure.com/scalesetpriority
    operator: Equal
    value: spot


resources: # NC6
  requests:
    cpu: 1
    memory: 10G
  limits:
    cpu: 5
    memory: 50G
    # nvidia.com/gpu: 1 # on demand I tuned it off # do not uncomment this or gpu pod doesn't come up 
  

affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.azure.com/accelerator
              operator: In
              values:
                - nvidia
        - matchExpressions:
          - key: topology.kubernetes.io/zone
            operator: In
            values:
            - eastus-1
        - matchExpressions:
            - key: instance-size
              operator: In
              values:
                - Standard_NC6s_v3
        # - matchExpressions:
        #   - key: kubernetes.io/hostname
        #     operator: In
        #     values:
        #     - aks-gpunc6-15667852-vmss00000p

livenessProbe:
readinessProbe:

volumeMounts:
  - mountPath: /mnt/ai-nfs
    name: ai-nfs
  - mountPath: /mnt/models-pvc
    name: models-pvc
  - mountPath: /mnt/workspace-pv
    name: workspace-pv
  - mountPath: /home/agent/models
    name: models-pvc
    subPath: models
  - mountPath: /home/agent/workspace
    name: workspace-pv
    subPath: workspace
  - mountPath: /home/agent/workspace/models
    name: workspace-pv
    subPath: models
  - mountPath: /home/agent/.vscode-server
    name: workspace-pv
    subPath: vscode-server
  # Shared memory
  - name: dshm
    mountPath: /dev/shm


volumes:
  - name: dshm
    emptyDir:
      medium: Memory
  - name: ai-nfs
    persistentVolumeClaim:
      claimName: generative-ai-pvc
  - name: workspace-pv
    persistentVolumeClaim:
      claimName: generative-work-pvc
  - name: models-pvc
    persistentVolumeClaim:
      claimName: models-pvc