replicaCount: 1
# debug: false # default is true

# command:
#   [
#     "sh",
#     "-c",
#     "tail -f /dev/null",
#   ]


command:
  [
    "sh",
    "-c",
    "sudo sed -e '62d' /etc/init.d/docker > /tmp/docker &&  sudo cp /tmp/docker  /etc/init.d/docker && sudo service docker start && tail -f /dev/null"
  ]


service:
  type: ClusterIP
  port: 8888
  name: docker-engine


image:
  repository: foundationmodels/docker-engine
  pullPolicy: IfNotPresent
  tag: base

env:
- name: PYTHONPATH
  value: /home/agent/workspace/MediNoteAI/src:/home/agent/workspace/MediNoteAI/tests        

ingress:
  enabled: false

# podSecurityContext:
#   runAsUser: 0
#   runAsGroup: 0

# securityContext:
#   privileged: false
#   runAsUser: 0
#   runAsGroup: 0



livenessProbe:
readinessProbe:

volumeMounts:
  # Shared memory
  - name: dshm
    mountPath: /dev/shm
  # - mountPath: /aidrive/datasets
  #   name: datasets-volume
  - mountPath: /mnt
    name: workspace-pvc
  - mountPath: /home/agent/workspace
    name: workspace-pvc
    subPath: workspace
  # comment from here if it is the first time to run the pod
  # - mountPath: /var/run/docker.sock
  #   name: docker-socket
  - mountPath: /var/lib/docker
    name: docker-pvc
    subPath: docker       
  # - mountPath: /root
  #   name: docker-volume 
  #   subPath: root    


volumes:
  - name: dshm
    emptyDir:
      medium: Memory
  - name: docker-pvc
    persistentVolumeClaim:
      claimName: docker-engine-pvc
  - name: workspace-pvc
    persistentVolumeClaim:
      claimName: generative-work-pvc
