replicaCount: 1
# debug: false # default is true

command:
  [
    "sh",
    "-c",
    "tail -f /dev/null",
  ]

# image:
#   repository: foundationmodels/vllm
#   pullPolicy: IfNotPresent
#   tag: latest-transformers


image:
  repository: ghcr.io/opendevin/opendevin
  pullPolicy: IfNotPresent
  tag: 0.6.2

service:
  type: ClusterIP
  port: 8888
  name: opendevin

env:
- name: SANDBOX_USER_ID=
  value: 1000

ingress:
  enabled: false

resources:
  requests:
    memory: "30Gi"
    cpu: "1"
  limits:
    memory: "32Gi"
    cpu: "4"


affinity:


tolerations:
  - key: "dedicated"
    operator: "Equal"
    value: "node-gpu"
    effect: "NoSchedule"
  - effect: NoSchedule
    key: kubernetes.azure.com/scalesetpriority
    operator: Equal
    value: spot

podSecurityContext:
  runAsUser: 1000
  runAsGroup: 1000

securityContext:
  runAsUser: 1000
  runAsGroup: 1000



volumeMounts:
  - mountPath: /mnt/models
    name: ai-llm
    subPath: models
  - mountPath: /mnt/datasets
    name: datasets-volume
  - mountPath: /mnt/aidrive/datasets
    name: datasets-volume
  - mountPath: /mnt/aidrive/models
    name: models-volume
  - mountPath: /mnt/ai-nfs
    name: ai-nfs
  - mountPath: /mnt/ai-llm
    name: ai-llm

  - mountPath: /home/agent/models
    name: ai-nfs
    subPath: models
  - mountPath: /home/agent/workspace
    name: ai-nfs
    subPath: workspace
  - mountPath: /home/agent/workspace/.vscode
    name: ai-nfs
    subPath: workspace/env-settings/settings/.vscode.hosseina
  - mountPath: /home/agent/.bashrc
    name: ai-nfs
    subPath: workspace/env-settings/.bashrc
  - mountPath: /home/agent/.bash_aliases
    name: ai-nfs
    subPath: workspace/env-settings/.bash_aliases
  - mountPath: /home/agent/.zshrc
    name: ai-nfs
    subPath: workspace/env-settings/.zshrc
  - mountPath: /home/agent/.vscode-server
    name: ai-nfs
    subPath: vscode-server
  # Shared memory
  - name: dshm
    mountPath: /dev/shm

volumes:
  - name: dshm
    emptyDir:
      medium: Memory
  - name: datasets-volume
    azureFile:
      secretName: storage-secret
      shareName: datasets
      readOnly: false
  - name: models-volume
    azureFile:
      secretName: storage-secret
      shareName: models
      readOnly: false
  - name: ai-nfs
    persistentVolumeClaim:
      claimName: ai-nfs
  - name: ai-llm
    persistentVolumeClaim:
      claimName: ai-llm

workingDir: /opt/workspace_base

