replicaCount: 1
# debug: false # default is true

# command:
#   [
#     "sh",
#     "-c",
#     "tail -f /dev/null",
#   ]

command:
  - "sh"
  - "-c"
  - |
    playwright install && \
    su opendevin -c "sudo service docker start" && \
    uvicorn opendevin.server.listen:app --host 0.0.0.0 --port 3000

image:
  repository: foundationmodels/opendevin
  pullPolicy: IfNotPresent
  tag: 0.6.2

service:
  type: ClusterIP
  port: 3000
  name: opendevin

env:
- name: SANDBOX_TYPE
  value: exec
- name: WORKSPACE_MOUNT_PATH
  value: /mnt/ai-nfs/workspace


podSecurityContext:
  runAsUser: 0
  runAsGroup: 0

securityContext:
  privileged: true
  runAsUser: 0
  runAsGroup: 0

workingDir: /app


ingress:
  enabled: false

resources:
  requests:
    memory: "30Gi"
    cpu: "1"
  limits:
    memory: "32Gi"
    cpu: "4"


affinity:


tolerations:
  - key: "dedicated"
    operator: "Equal"
    value: "node-gpu"
    effect: "NoSchedule"
  - effect: NoSchedule
    key: kubernetes.azure.com/scalesetpriority
    operator: Equal
    value: spot




volumeMounts:
  - mountPath: /mnt/ai-nfs
    name: ai-nfs
  - mountPath: /opt/workspace_base
    name: ai-nfs
    subPath: workspace
  - mountPath: /home/agent/workspace
    name: ai-nfs
    subPath: workspace
  # Shared memory
  - name: dshm
    mountPath: /dev/shm

volumes:
  - name: dshm
    emptyDir:
      medium: Memory
  - name: ai-nfs
    persistentVolumeClaim:
      claimName: ai-nfs


