replicaCount: 1
# debug: false # default is true

command:
  [
    "sh",
    "-c",
    "tail -f /dev/null",
  ]

# image:
#   repository: foundationmodels/vllm
#   pullPolicy: IfNotPresent
#   tag: latest-transformers


image:
  repository: foundationmodels/vllm
  pullPolicy: IfNotPresent
  tag: may

service:
  type: ClusterIP
  port: 8888
  name: sandbox

env:
- name: PYTHONPATH
  value: /home/agent/workspace/ai-narrative-gen/src:/home/agent/workspace/query2sql2api/src:/home/agent/workspace/MediNoteAI/src/FastChat:/home/agent/workspace/MediNoteAI/src/llama_index:/home/agent/workspace/MediNoteAI/src         

ingress:
  enabled: false

resources:
  requests:
    memory: "30Gi"
    cpu: "1"
  limits:
    memory: "32Gi"
    cpu: "4"


affinity:


tolerations:
  - key: "dedicated"
    operator: "Equal"
    value: "node-gpu"
    effect: "NoSchedule"
  - effect: NoSchedule
    key: kubernetes.azure.com/scalesetpriority
    operator: Equal
    value: spot

podSecurityContext:
  runAsUser: 1000
  runAsGroup: 1000

securityContext:
  runAsUser: 1000
  runAsGroup: 1000


volumeMounts:
  - mountPath: /mnt/ai-nfs
    name: ai-nfs
  - mountPath: /home/agent/workspace
    name: ai-nfs
    subPath: workspace
  - mountPath: /mnt/models
    name: ai-nfs
    subPath: models
  - mountPath: /dev/shm
    name: dshm

volumes:
  - emptyDir:
      medium: Memory
    name: dshm
  - name: ai-nfs
    persistentVolumeClaim:
      claimName: aifile8-pvc


