replicaCount: 1
# debug: false # default is true

command:
  [
    "sh",
    "-c",
    "tail -f /dev/null",
  ]

image:
  repository: foundationmodels/vllm
  pullPolicy: IfNotPresent
  tag: latest-transformers

env:
- name: PYTHONPATH
  value: /home/agent/workspace/MediNoteAI/src:/home/agent/workspace/MediNoteAI/tests        

ingress:
  enabled: false

resources:
  requests:
    memory: "2Gi"
    cpu: "1"
  limits:
    memory: "8Gi"
    cpu: "2"

tolerations:

affinity:

podSecurityContext:
  runAsUser: 1000
  runAsGroup: 1000

securityContext:
  runAsUser: 1000
  runAsGroup: 1000


volumeMounts:
  - mountPath: /mnt/models
    name: ai-llm
    subPath: models
  - mountPath: /mnt/datasets
    name: datasets-volume
  - mountPath: /mnt/aidrive/datasets
    name: datasets-volume
  - mountPath: /mnt/aidrive/models
    name: models-volume
  - mountPath: /mnt/aidrive/mlflow
    name: mlflow-volume
  - mountPath: /mnt/ai-nfs
    name: ai-nfs
  - mountPath: /mnt/ai-llm
    name: ai-llm
  - mountPath: /mnt/models-nfs
    name: models-nfs
  - mountPath: /home/agent/models
    name: ai-nfs
    subPath: models
  - mountPath: /home/agent/workspace
    name: ai-nfs
    subPath: workspace
  - mountPath: /home/agent/workspace/.vscode
    name: ai-nfs
    subPath: workspace/ubuntu-configs/settings/.vscode.mistral
  - mountPath: /home/agent/.bashrc
    name: ai-nfs
    subPath: workspace/ubuntu-configs/.bashrc
  - mountPath: /home/agent/.zshrc
    name: ai-nfs
    subPath: workspace/ubuntu-configs/.zshrc
  - mountPath: /home/agent/.vscode-server
    name: ai-llm
    subPath: vscode-server-mistral
  # Shared memory
  - name: dshm
    mountPath: /dev/shm

volumes:
  - name: dshm
    emptyDir:
      medium: Memory
  - name: datasets-volume
    azureFile:
      secretName: storage-secret
      shareName: datasets
      readOnly: false
  - name: models-volume
    azureFile:
      secretName: storage-secret
      shareName: models
      readOnly: false
  - name: mlflow-volume
    azureFile:
      secretName: storage-secret
      shareName: mlflow
      readOnly: false
  - name: ai-nfs
    persistentVolumeClaim:
      claimName: ai-nfs
  - name: models-nfs
    persistentVolumeClaim:
      claimName: ai-models-nfs
  - name: ai-llm
    persistentVolumeClaim:
      claimName: ai-llm


