apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: models-pvc
  labels:
    Prouct: ai
    Environment: dev
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: ai-disk-sc
  resources:
    requests:
      storage: 800Gi
  