latest_transformers:
	@echo "Downloading latest transformers from Hugging Face"
	@pip install git+https://github.com/huggingface/transformers.git
	@echo "Download complete"
.PHONY: latest_transformers